version: "3"

services:
  db:
    image: mysql
    container_name: mysql-container
    restart: always
    ports:
      - 3306:3306
    env_file:
      - /.env
    volumes:
      - sqlData:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - db
    env_file:
      - /.env
    ports:
      - 8000:80
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: backend-api
    depends_on:
      - db
    env_file:
      - /.env
    ports:
      - 5000:5000
    networks:
      - app-network
    volumes:
      - //g/backend/Digital-wallet:/backend
      - /backend/node_modules

networks:
  app-network:

volumes:
  sqlData:
